@startuml
header Singleton Version 1
footer Singleton Version 1
title Singleton Diagram

class Singleton {
    - {static} Singleton instance
    - Singleton()
    + {static} Singleton getInstance()
}

class Client {}

Client --> Singleton : calls getInstance()

@enduml